name: Test Programs

on: [push, pull_request]

jobs:
    runTests:
        name: Test ${{ matrix.data.name }} Impl
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                data:
                    [
                        { name: Main, command: main, wildcard: compute_*.txt },
                        {
                            name: Main Quiet,
                            command: main_quiet,
                            wildcard: aggregated_*.txt,
                        },
                        { name: MPI, command: main_mpi, wildcard: mpi_*.txt },
                        { name: MPI2, command: main_mpi2, wildcard: mpi_*.txt },
                        {
                            name: MPI2 Mem,
                            command: main_mpi2_mem,
                            wildcard: mpi_*.txt,
                        },
                        {
                            name: Threaded,
                            command: main_threaded,
                            wildcard: thread_*.txt,
                        },
                    ]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup MPI
              if: contains(matrix.data.name, 'MPI')
              uses: mpi4py/setup-mpi@v1
              with:
                  mpi: "openmpi"
            - name: Compile Program
              run: make ${{ matrix.data.command }}
            - name: Run Program
              run: bash ./run_program.sh ${{ matrix.data.command }} 0 50000 10000
            - name: Verify Output
              run: diff <(grep -h " | " ./${{ matrix.data.wildcard }} | sort) <(cat ./tests/test_0_50000.txt | sort)
